# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference

# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Android orb documentation here: https://circleci.com/developer/orbs/orb/circleci/android
  android: circleci/android@3.0.1

  # See the CodeCov orb documentation here: https://circleci.com/developer/orbs/orb/codecov/codecov
  codecov: codecov/codecov@5.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define the Android machine image executor.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/developer/orbs/orb/circleci/android#executors-android-machine
    executor:
      name: android/android_machine
      tag: default

    steps:
      - checkout

      - android/restore_build_cache

      - android/restore_gradle_cache:
          find_args: . -name "build.gradle*" -o -name "settings.gradle*" -o -name "libs.versions.toml"

      - android/run_tests:
          test_command: ./gradlew check

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

      # Save lint report
      - store_artifacts:
          path: ./troupe/build/reports/lint-results-debug.html

      # Save unit test results
      - store_test_results:
          path: ./troupe/build/test-results/testDebugUnitTest

      - codecov/upload:
          files: troupe/build/reports/kover/report.xml

      - android/save_gradle_cache

      - android/save_build_cache

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-check: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
