name: Publish to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Check to publish locally. Useful for testing.'
        type: boolean
        default: false
        required: false

jobs:
  publish-gpr:
    runs-on: macos-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Dry run: ${{ inputs.dry-run }}"

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build

      - name: Publish to local maven repo
        run: |
          ./gradlew publishAllPublicationsToProjectLocalRepository

      - name: Upload artifacts to action summary
        run: ./gradlew archiveAllPublicationsFromProjectLocalRepository

      - name: Publish artifacts to GitHub Packages
        env:
          GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
          GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
        if: ${{ inputs.dry-run != true }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
